README.md
lib/i2c.ex
lib/i2c/i2c_nif.ex
src/i2c_nif.c
src/i2c_nif.h
src/i2c_nif_res_list.c

Replaced integer file descriptor with references to identify channels when reading and writing data.  Copied the ElixirALE interface.  Default i2c node address is specified on open(), and does not need to be specified on subsequent read(), write(), and write_read() calls.  read_device(), write_device(), and write_read_device() functions are available if other i2c nodes need to be addressed using the same channel reference.
Calling the close() function releases the resources attached to the given reference, but does not close the i2c device file, in case there is more than one process using the i2c bus.

Use references to identify channels.  Copy ElixirALE interface

---

README.md
RELEASE.md
lib/i2c/i2c_nif.ex
mix.exs
src/i2c_nif.c
src/i2c_nif_res_list.c

While I was renaming, I made a number of minor updates to docs. See the "rename app" commit for the big rename.

Rename the app from i2c -> elixir_circuits_i2c

---

Makefile
lib/i2c.ex
src/hal_i2cdev.c
src/hal_stub.c
src/i2c_nif.c
src/i2c_nif.h

This makes it possible to compile and "run" on OSX for test purposes.
The stub is currently minimal and HAL API will likely need additions if
non-Linux platforms are ever supported.
WIP Note: I haven't tested on Linux or Nerves. Once this PR gets to a good place, I'd like to do something similar on the other platforms. For GPIO, it will open up supporting non-Raspberry Pi platforms. 
While I was refactoring, I made a couple changes that should be reviewed:
1. On I2C errors, I'm returning the errno value rather than a generic "access denied", "write failed" etc. 
2. I added a call to close() when close is called. I assume that got accidentally dropped at some point.

Refactor platform-specific parts and add stub

---

README.md
lib/i2c.ex
lib/i2c/i2c_nif.ex
src/i2c_nif.c

This PR addresses #9 by removing the I2C device address from the NIF. It requires #8 to be merged first. In the meantime, it's easiest to review the second commit below.

Simplify api

---

lib/i2c.ex

This makes it possible to pass lists (probably convenient for Erlang)
and iolists in addition to binaries.
I ran into a situation where I was constructing a message and then prepending it with a length field and suffixing it with a crc16. Using iolists for this was really convenient.

Support iodata being passed to writes

---

lib/i2c.ex

What do you think about removing the `i2c_` from `i2c_bus()` and `i2c_address()`?
In my code, I'm typing `Circuits.I2C.i2c_address()` and `Circuits.I2C.i2c_bus()` in my typespecs. (Actually `I2C.i2c_address()` when I have the alias). It feels redundant. `I2C.bus()` and `I2C.address()` look nicer in my code. I'm wondering if you two feel the same.

Remove i2c_ from i2c_address and i2c_bus

---

lib/i2c.ex

`I2C.detect_devices/0` would give a helpful error message about how to
properly call it with the bus number. This commit changes that to print
out all of the detected devices. The new output looks like this:
```
iex> I2C.detect_devices
Devices on I2C bus "i2c-0":
Devices on I2C bus "i2c-1":
* 60
1 devices detected on 2 I2C buses
```

Print detected devices instead of an error

---

src/i2c_nif.c

This fixes a file handle leak whenever GC collected a I2C bus reference.

Add destructor to close file handle to i2c bus

---

README.md

Circuits.I2C.detect_devices/0 may be more applicable in the debugging section and as the first detect_devices command people should try.
Sometimes `Circuits.I2C.detect_devices/1` can display funny in iex. For example, if there's a device at 64 and 112 the return displays as `'@p'`.

Update README to reference I2C.detect_devices/0

---

src/hal_stub.c
src/i2c_nif.c
test/circuits_i2c_test.exs

It now says something about the bus not being found.
Fixes #37

Improve error message when opening unknown bus

---

.circleci/config.yml
mix.exs
mix.lock

This adds a link back to the source code from the docs and prevents ex_doc from being compiled in normal development.

Refactor doc generation

---

.circleci/config.yml
Makefile
lib/i2c.ex
mix.exs
mix.lock

The `i2cdetect` utility only polls 0x03 to 0x77 when detecting devices. It
seems reasonable to limit detection to those addresses especially since a
report was made today that `i2cdetect` worked and
`Circuits.I2C.detect_devices/1` caused an I2C bus hang. This appeared to be
due to a microcontroller not being happy, but it seems safer to limit the
range going forward especially since pretty much all devices are in the
reduced range anyway.

Restrict addresses polled by detect_devices

---

README.md
lib/i2c.ex

Sometimes it's easier to cross reference with a datasheet if you can quickly see the detected devices in hex instead of decimal. This will add the output on the terminal in hex as well.

Show hex value for detected devices

---

.circleci/config.yml

This also drops some old builds since it seems like they haven't been
seen in the wild for a long time.

CI: switch to hexpm images and add Elixir 1.11

---

lib/i2c.ex
src/hal_stub.c
test/circuits_i2c_test.exs

This PR builds off #64 to add an optional detection function and add unit tests. The detection function lets users do something device-specific like query an ID register.
@batate - I squashed and rebased your PR to the first commit in the PR. Yesterday I made it possible to have unit tests for simple things with Circuits.I2C so I went ahead and added unit tests for the `discover*` functions. That's in the second commit for this PR. I believe that I didn't do anything to break any of the use cases that you outlined in #64. Could you take a look when you get a chance?

Squash #64, add optional detection function, add tests

---

lib/i2c.ex

It turns out that waiting for GC to collect open handles wasn't always
quick enough. This closes a handle when discovering devices and prevents
too many from being opened simultaneously. This does not seem like an
issue that people would run into with normal use.

Fix intermittent CI issue due to too many open handles

---

mix.exs

`src` was changed to `c_src`, but this formatting helper was missed so `astyle` would never run

Fix `format_c` to reference `c_src` directory

---

lib/i2c.ex

This is how the i2c-tools package detects devices, and it actually is
able to detect at least one more device than the original read method.
The i2c-tools comments warn that 0-byte writes are known to corrupt some
EEPROMs and the single byte reads are known to confuse write-only
devices. This copies the heuristic of using reads on the common EEPROM
addresses.

Detect some addresses by using 0-length writes

---

c_src/i2c_nif.c
lib/i2c.ex
lib/i2c/i2c_nif.ex
test/i2c/i2c_nif_test.exs

This fixes an issue where an I2C controller doesn't support zero byte
writes and then fails to detect on some I2C addresses.

Detect zero-byte write and adjust device detection

---

lib/i2c.ex

This was present in v1.0 but moved to `Circuits.I2C.Bus.t()` in v2.0 which causes some errors when migrating.
For convenience, this adds the spec back to the top level `Circuits.I2C` that referenves the new spec

Add `Circuits.I2C.bus()` spec back

---

lib/i2c/i2c_nif.ex

This change moves the NIF load from the time at which the module is
loaded to the time when a I2C actually is used.
The primary motivation for doing this is to defer native code crashes
from happening at load time to the time of first use. Load time is
harder to debug and sometimes its not clear which NIF caused the crash.
The calls to `apply` get around some complexity with ignoring Dialyzer
warnings. Dialyzer can't figure out that the recursive looking call
actually invokes the NIF code.

Defer loading the NIF until opening an I2C bus

---

lib/i2c/i2c_nif.ex
test/circuits_i2c_test.exs

Interestingly, the unit test was able to segfault before this fix.

Fix race when two process load the NIF at the same time

---

mix.exs

It turns out that people sometimes have MIX_TARGET set when they're not
compiling for Nerves. On MacOS which doesn't support i2c_dev, this
causes the following error:
```
==> circuits_i2c
"**** CIRCUITS_I2C_BACKEND set to [normal] ****"
Makefile:44: *** Circuits.I2C Linux i2c-dev backend is not supported on non-Linux platforms. Review circuits_i2c backend configuration or report an issue if improperly detected..  Stop.
could not compile dependency :circuits_i2c, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile circuits_i2c --force", update it with "mix deps.update circuits_i2c" or clean it with "mix deps.clean circuits_i2c"
```
This is pretty confusing. This change makes the Nerves detection smarter
by first checking the …

Improve target detection for building i2c_dev

---

lib/i2c.ex

This happens when I2C calls fail for unexpected reasons like `{:errno, 6}`.

Inspect error reasons to support tuple errors
